---

  - import_tasks: system_packages.yml

#  - import_tasks: hostname.yml

#- include: timezone.yml
#  tags: timezone

#- include: root_password.yml
#  tags: root-password

#- include: hosts_file.yml
#  tags: hosts_file

