---

  - name: Make sure yum mount directory exists
    file:
      path: "{{repo_mount}}"
      state: "directory"

  - name: Make sure yum repo is in fstab
    lineinfile:
      path: "/etc/fstab"
      line: '{{repo_share}} {{repo_mount}} cifs nobrl,username={{repo_user}},password={{repo_passwd}},uid=110,gid=120,rw,suid 0 0'
      regexp: '^{{repo_share}} {{repo_mount}} cifs nobrl,username={{repo_user}},password={{repo_passwd}},uid=110,gid=120,rw,suid 0 0'

#  - name: Mount yum share
#    mount:
#      path: "{{repo_mount}}"
#      state: "mounted"
#      src: "{{repo_share}}"
#      fstype: "cifs"

#  - name: "Mount {{repo_mount}}"
#    shell: "mount {{repo_mount}}"
#    ignore_errors: "yes"

  - name:  Make sure yum repo is mounted
    mount:
      path: "/yum_repo"
      state: "mounted"
      fstype: "cifs"
      src: "//mycloudnas/yum_repos"
      opts: "nobrl,username=guest,password=,uid=110,gid=120,rw,suid"

  - name: temp
    file:
      path: "/etc/yum.repos.d"
      state: "directory"
      owner: "root"
      mode: 0755

  - name: Remove all repos
    file:
      path: "/etc/yum.repos.d/*"
      state: "absent"
    when: '"local_update" in group_names'

  - name: Push base repo config
    template:
      src: "CentOS-Base.repo.j2"
      dest: "/etc/yum.repos.d/CentOS-Base.repo"
      owner: "root"
      mode: "0755"
    when: '"local_update" in group_names'
    
  - name:  Make sure yum repo is unmounted
    mount:
      path: "/yum_repo"
      state: "unmounted"
