---

  - name: Install openvpn
    yum:
      name: "{{item.vpnpkg}}"
    with_items:
      "{{vpnpkgs}}"

  - name: Untar openvpn configs
    unarchive:
      src: "{{ artifact_repo }}openvpn/pc-openvpnserver.tgz"
      dest: "/etc/openvpn"