---

  - name: Install openvpn
    yum:
      name: "{{item.vpnpkg}}"
    with_items:
      "{{vpnpkgs}}"

  - name: Enable OpenVPN
    service: 
      name: "openvpn@server"
      state: "started"
      enabled: "yes"

  - name: Untar openvpn configs
    unarchive:
      src: "{{ artifact_repo }}openvpn/pc-openvpnserver.tar.gz"
      dest: "/etc/openvpn"

#  - name: Open firewall to OpenVPN
#    firewalld:
#      service: openvpn
#      permanent: true
#      state: enabled
#    notify: RestartFirewalld