---

  - name: Install openvpn
    yum:
      name: "{{item.vpnpkg}}"
    with_items:
      "{{vpnpkgs}}"

  - name: Enable OpenVPN
    service: 
      name: "openvpn@server"
      state: "started"
      enabled: "yes"

  - name: Untar openvpn configs
    unarchive:
      src: "{{ artifact_repo }}openvpn/pc-openvpnserver.tar.gz"
      dest: "/etc/openvpn"

  - name: Open firewall to OpenVPN
    firewalld:
      service: openvpn
      permanent: true
      state: enabled
    notify: RestartFirewalld

  - name: Allow traffic between networks through FORWRD iptables chain via firewalld
    command: "firewall-cmd --direct --add-rule ipv4 filter FORWARD 0 -o tun0 -i ens192 --permanent -j ACCEPT"  

  - name: enable forwarding in the kernel
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes