---

  - name: Set Hostname
    shell: hostnamectl set-hostname "{{ hostname }}"

  - name: Copy network config jinja template
    template:
      src: "ifcfg-ens192.j2"
      dest: :/etc/sysconfig/network-scripts/ifcfg-{{device}}"
      backup: "yes"
