---

  - name: Install base system packages
    yum:
      name={{item}}
      state=latest
    with_items: 
      - {{packages}}
    tags:
      - system_packages
    when:
      ansible_os_family == "RedHat"

