---

  - name: Install base system packages
    yum:
      name={{item}}
      state=latest
    with_items: 
      {{packages}}
    tags:
      - system_packages
    when:
      ansible_os_family == "RedHat"


#TODO
#Make sure we do or dont need the following packages for Ubuntu
#- libselinux-python
#- policycoreutils-python
#  - name: Install base system packages
#    apt:
#      name={{item}}
#      state=latest
#    with_items: 
#      - policycoreutils
#      - screen
#      - vim
#      - tmux
#      - htop
#      - iftop
#    tags:
#      - system_packages
#    when:
#      ansible_os_family == "Debian"