---

  - name: Install DNS Packages
    yum:
      name: "{{ item.dnspkg }}"
      state: "latest"
    when: packages is defined
    with_items:
      - "{{ dnspkgs }}"

  - name: Copy forward powellcompanies zone file
    copy:
      src: "powellcompanies.com.zone"
      dest: "/var/named/chroot/etc/"
      backup: "yes"
      owner: "root"
      group: "named"
      mode: "750"

  - name: Copy reverse powellcompanies zone file
    copy:
      src: "powellcompanies.com.rev.zone"
      dest: "/var/named/chroot/etc/"
      backup: "yes"
      owner: "root"
      group: "named"
      mode: "750"

  - name: Copy named.conf template
    template:
      src: "named.conf.j2"
      dest: "/etc/named.conf"
      backup: "yes"
      owner: "root"
      group: "named"
      mode: "640"
      validate: "named-checkconf %s"
    notify: RestartNamed

  - name: Open firewall to DNS op local net
    firewalld:
      service: dns
      source: 192.168.3.0/24
      permanent: true
      state: enabled

  - name: Open firewall to DNS to vpn net
    firewalld:
      service: dns
      source: 192.168.2.0/24
      permanent: true
      state: enabled

  - name: Set selinux to allow user named to create journal files
    shell: "chcon -R -t dnssec_trigger_var_run_t /var/named/chroot/etc/named/"
    