---

  - name: Install DNS Packages
    yum:
      name: "{{ item.dnspkg }}"
      state: "latest"
    when: packages is defined
    with_items:
      - "{{ dnspkgs }}"

  - name: Copy forward powellcompanies zone file
    copy:
      src: "powellcompanies.com.zone"
      dest: "/var/named/chroot/etc/"
      backup: "yes"
      owner: "root"
      group: "named"
      mode: "750"

  - name: Copy reverse powellcompanies zone file
    copy:
      src: "powellcompanies.com.rev.zone"
      dest: "/var/named/chroot/etc/"
      backup: "yes"
      owner: "root"
      group: "named"
      mode: "750"

  - name: Copy named.conf template
    template:
      src: "named.conf.j2"
      dest: "/etc/named.conf"
      backup: "yes"
      owner: "root"
      group: "named"
      mode: "640"
      validate: "named-checkconf %s"
    notify: RestartNamed
    