---

  - name: Install DNS Packages
    yum:
      name: "{{ item.dnspkg }}"
      state: "latest"
    when: packages is defined
    with_items:
      - "{{ dnspkgs }}"

  - name: Copy named.conf template
    template:
      src: "named.conf.j2"
      dest: "/etc/named.conf"
      backup: "yes"
      owner: "root"
      group: "named"
      mode: "640"