---

  - name:  Make sure yum repo is mounted
    mount:
      path: "/yum_repo"
      state: "mounted"
      fstype: "cifs"
      src: "//mycloudnas/yum_repos"
      opts: "nobrl,username=guest,password=,uid=110,gid=120,rw,suid"
    
  #- name: Install required Packages
  #  yum:
  #    name: "{{item}}"
  #    state: latest
  #  with_items:
  #    - yum-utils
  #    - createrepo

  - name: Sync CentOS 7 Base Repository
    shell: reposync -d --gpgcheck -l --repoid=base --download_path={{repo_path}} --downloadcomps --download-metadata
    async: 3600
    poll: 10

  - name: Update CentOS 7 Base Repository
    shell: createrepo --update {{repo_path}}/base
    async: 3600
    poll: 10

  - name: Sync CentOS 7 EPEL Repository
    shell: reposync -d --gpgcheck -l --repoid=epel --download_path={{repo_path}} --downloadcomps --download-metadata
    async: 3600
    poll: 10

  - name: Update CentOS 7 EPEL Repository
    shell: createrepo --update {{repo_path}}/epel
    async: 3600
    poll: 10

  - name: Sync CentOS 7 Updates Repository
    shell: reposync -d --gpgcheck -l --repoid=updates --download_path={{repo_path}} --downloadcomps --download-metadata
    async: 3600
    poll: 10

  - name: Update CentOS 7 Updates Repository
    shell: createrepo --update {{repo_path}}/updates
    async: 3600
    poll: 10

  - name: Sync CentOS 7 Extras Repository
    shell: reposync -d --gpgcheck -l --repoid=extras --download_path={{repo_path}} --downloadcomps --download-metadata
    async: 3600
    poll: 10

  - name: Update CentOS 7 Extras Repository
    shell: createrepo --update {{repo_path}}/extras
    async: 3600
    poll: 10

  - name:  Make sure yum repo is unmounted
    mount:
      path: "/yum_repo"
      state: "unmounted"