---
  - name: Install required Packages
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - yum-utils
      - createrepo

  - name: Sync CentOS 7 Yum Repository
    shell: reposync -d --gpgcheck -l --repoid=base --download_path={{repo_mount}} --downloadcomps --download-metadata