---

  - name:  Make sure yum repo is mounted
    mount:
      path: "/yum_repo"
      state: "mounted"
      fstype: "cifs"
      src: "//mycloudnas/yum_repos"
      opts: "nobrl,username=guest,password=,uid=110,gid=120,rw,suid"

  - name: Update all installed packages
    yum:
      name: "*"
      update_cache: "yes"
      state: "latest"

  - name:  Make sure yum repo is unmounted
    mount:
      path: "/yum_repo"
      state: "unmounted"

