---

  - name:  Make sure yum repo is mounted
    mount:
      path: "/yum_repo"
      state: "mounted"

  - name: Update all installed packages
    yum:
      name: "*"
      update_cache: "yes"
      state: "latest"